import Foundation

#if canImport(UIKit)
import UIKit
/// Platform image type returned by ``RetentionFlow/qrCode(for:size:theme:referralCode:)``.
public typealias RetentionFlowImage = UIImage
#elseif canImport(AppKit)
import AppKit
/// Platform image type returned by ``RetentionFlow/qrCode(for:size:theme:referralCode:)``.
public typealias RetentionFlowImage = NSImage
#endif

// MARK: - Flow QR codes
//
// A pretty, out-of-the-box QR code for any flow's public page, with the app's
// logo centred — generated by AppMate and served as PNG/SVG. The host app just
// needs the URL (for AsyncImage / a remote image loader) or a ready image to
// drop into a "Scan to …" surface. Customisation (colours, dot styles) is
// configured per flow in the dashboard; the SDK only points at the result.

extension RetentionFlow {

    /// A flow whose public page can be encoded as a QR code. Raw values match
    /// the AppMate QR endpoint path segment.
    public enum QRFlow: String, Sendable {
        case cancel, waitlist, feedback, report, contact
        case onboarding, wishlist, link, referral
    }

    /// QR colour scheme. `.auto` matches the flow's configured colour scheme.
    public enum QRTheme: String, Sendable {
        case auto, light, dark
    }

    /// URL of a flow's QR image. Hand this to SwiftUI's `AsyncImage` or any
    /// remote-image loader. Returns `nil` if ``configure(_:)`` wasn't called.
    ///
    /// - Parameters:
    ///   - flow: Which flow's public page to encode.
    ///   - png: `true` for a PNG (default), `false` for a scalable SVG.
    ///   - size: Pixel edge of the PNG (ignored for SVG). Default 512.
    ///   - theme: `.auto` (match the flow), or force `.light` / `.dark`.
    ///   - referralCode: For `.referral`, the referrer's code so the QR encodes
    ///     that specific invite link (e.g. from ``referralShareCode(userId:)``).
    public static func qrCodeURL(
        for flow: QRFlow,
        png: Bool = true,
        size: Int = 512,
        theme: QRTheme = .auto,
        referralCode: String? = nil
    ) -> URL? {
        guard let config = config else { return nil }
        let endpoint = qrWebBaseURL(from: config)
            .appendingPathComponent("api/public/qr")
            .appendingPathComponent(config.appSlug)
            .appendingPathComponent(flow.rawValue)
        guard
            var comps = URLComponents(url: endpoint, resolvingAgainstBaseURL: false)
        else { return nil }
        var items = [
            URLQueryItem(name: "format", value: png ? "png" : "svg"),
            URLQueryItem(name: "size", value: String(size)),
        ]
        if theme != .auto {
            items.append(URLQueryItem(name: "theme", value: theme.rawValue))
        }
        if let referralCode, !referralCode.isEmpty {
            items.append(URLQueryItem(name: "code", value: referralCode))
        }
        comps.queryItems = items
        return comps.url
    }

    #if canImport(UIKit) || canImport(AppKit)
    /// Fetch a flow's QR as a ready-to-display image (PNG). Returns `nil` on a
    /// network/decoding failure or if the SDK isn't configured.
    ///
    /// ```swift
    /// if let img = await RetentionFlow.qrCode(for: .waitlist) {
    ///     imageView.image = img
    /// }
    /// ```
    public static func qrCode(
        for flow: QRFlow,
        size: Int = 512,
        theme: QRTheme = .auto,
        referralCode: String? = nil
    ) async -> RetentionFlowImage? {
        guard
            let url = qrCodeURL(
                for: flow, png: true, size: size, theme: theme,
                referralCode: referralCode)
        else { return nil }
        do {
            let (data, response) = try await URLSession.shared.data(from: url)
            if let http = response as? HTTPURLResponse,
               !(200..<300).contains(http.statusCode) {
                return nil
            }
            return RetentionFlowImage(data: data)
        } catch {
            return nil
        }
    }
    #endif
}

// Apex host for the QR endpoint: explicit `webBaseURL` if set, else `baseURL`
// with a leading `cancel.` / `flow.` / `signup.` label removed. Mirrors
// RetentionFlowMenu's resolver but lives here (pure Foundation) so QR works on
// macOS, where the menu's UIKit-gated copy isn't compiled.
private func qrWebBaseURL(from config: RetentionFlowConfig) -> URL {
    if let explicit = config.webBaseURL { return explicit }
    guard
        var comps = URLComponents(url: config.baseURL, resolvingAgainstBaseURL: false),
        let host = comps.host
    else { return config.baseURL }
    for prefix in ["cancel.", "flow.", "signup."] where host.hasPrefix(prefix) {
        comps.host = String(host.dropFirst(prefix.count))
        return comps.url ?? config.baseURL
    }
    return config.baseURL
}

#if canImport(SwiftUI)
import SwiftUI

/// Drop-in SwiftUI view that loads and displays a flow's QR code. The simplest
/// way to present one — e.g. in a "Share with a friend" or "Scan to join" sheet:
///
/// ```swift
/// RetentionFlowQRView(flow: .referral, referralCode: code)
///     .frame(width: 220, height: 220)
/// ```
public struct RetentionFlowQRView: View {
    private let flow: RetentionFlow.QRFlow
    private let size: CGFloat
    private let theme: RetentionFlow.QRTheme
    private let referralCode: String?

    public init(
        flow: RetentionFlow.QRFlow,
        size: CGFloat = 220,
        theme: RetentionFlow.QRTheme = .auto,
        referralCode: String? = nil
    ) {
        self.flow = flow
        self.size = size
        self.theme = theme
        self.referralCode = referralCode
    }

    public var body: some View {
        AsyncImage(
            url: RetentionFlow.qrCodeURL(
                for: flow,
                png: true,
                // Render at ~3× for crisp display on retina screens.
                size: Int(size * 3),
                theme: theme,
                referralCode: referralCode
            )
        ) { phase in
            switch phase {
            case .success(let image):
                image.resizable().scaledToFit()
            case .failure:
                Color.clear
            default:
                ProgressView()
            }
        }
        .frame(width: size, height: size)
    }
}
#endif
